Add technical article: Using Aspose.Imaging for Java in Kotlin
aspose-imaging/Aspose.Imaging-Documentation pull request #19
Opened 2023-12-20 12:53 UTC by anms23

IMAGINGJAVA-8614: article about the possibility of using Aspose.Imaging for Java in Kotlin

2023-12-21 08:17 UTC, ESidenko commented
Perhaps the better to change "As of version 23.12" with "For now"

2023-12-21 08:18 UTC, ESidenko requested changes
Perhaps the better to change "As of version 23.12" with "For now"

2023-12-21 08:18 UTC, ESidenko commented on java/developer-guide/technical-articles/using-imaging-in-kotlin/_index.md
> +In the dynamic landscape of software development, the synergy between programming languages is a powerful force. Kotlin, known for its conciseness and interoperability with Java, opens doors for deve
Perhaps the better to change "As of version 23.12" with "For now"

2023-12-21 08:39 UTC, anms23 commented on java/developer-guide/technical-articles/using-imaging-in-kotlin/_index.md
> +In the dynamic landscape of software development, the synergy between programming languages is a powerful force. Kotlin, known for its conciseness and interoperability with Java, opens doors for deve
Fixed: https://github.com/aspose-imaging/Aspose.Imaging-Documentation/pull/19/commits/85dd6982e17dc397b4f74a8ea02617218a7ba741

2023-12-22 09:46 UTC, ESidenko approved these changes

2023-12-22 09:47 UTC, merged